---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(scales)
library(lubridate)
library(readxl)
library(janitor)
library(countrycode)
theme_set(theme_light())

qog_bas_cs_raw <- read_csv("qog_bas_cs_jan21.csv")
qog_bas_ts_raw <- read_csv("qog_bas_ts_jan21.csv")
bti_scores_raw <- read_excel("BTI 2020 Scores.xlsx") %>% clean_names() %>% rename("country" = "regions_1_east_central_and_southeast_europe_2_latin_america_and_the_caribbean_3_west_and_central_africa_4_middle_east_and_north_africa_5_southern_and_eastern_africa_6_post_soviet_eurasia_7_asia_and_oceania")
eiu_democracy_index_raw <- read_excel("economist_intel_unit_democracy_index.xlsx") %>% clean_names()
```


```{r}
qog_bas_selected <- qog_bas_cs_raw %>% 
  select(ccode, cname, ccodealp, icrg_qog, qs_closed, qs_impar, qs_proff) %>% 
  mutate(country = countrycode(ccodealp, origin = "iso3c", destination = "country.name")) %>% 
  mutate(country = recode(country, "Myanmar (Burma)" = "Myanmar"))

```

```{r}
bti_selected <- bti_scores_raw %>% 
  select(country, starts_with("q14")) 

bti_selected %>% 
  pivot_longer(-country, names_to = "category") %>% 
  ggplot(aes(category, value)) +
  geom_boxplot()
```

```{r}
eiu_selected <- eiu_democracy_index_raw %>% 
  select(country, func_tioning_of_govern_ment) %>% 
  mutate(country = str_trim(country)) %>% 
  mutate(country = recode(country, "Myanmar" = "Myanmar (Burma)", 
                          "Bosnia and Herzegovina" = "Bosnia & Herzegovina", 
                          "Hong Kong" = "Hong Kong SAR China")) %>% 
  rename("functioning_of_government" = "func_tioning_of_govern_ment")
```

## Plotting China's position on bureaucracy index

```{r}
index_joined <- gdi_selected %>% 
  mutate(country = countrycode(country_code, origin = "iso3c", destination = "country.name")) %>%
  left_join(bti_selected, by = "country") %>% 
  left_join(qog_bas_selected, by = "country") %>% 
  left_join(eiu_selected, by = "country") %>% 
  select(country, gov_effectiveness, q14_steering_capability, qs_impar, functioning_of_government) %>% 
  mutate(across(-country, ~ as.numeric(rescale(., to = c(-1, 1)))))

index_joined %>% summary()
```

```{r}
china_index_joined <- index_joined %>% 
  filter(country == "China") %>% 
  pivot_longer(-country, names_to = "category") %>% 
  mutate(category = fct_recode(category, 
                               "WGI" = "gov_effectiveness",
                               "EIU" = "functioning_of_government",
                               "BTI" = "q14_steering_capability", 
                               "QOG" = "qs_impar")) 

index_joined %>% 
  pivot_longer(-country, names_to = "category") %>% 
  mutate(category = fct_recode(category, 
                               "WGI" = "gov_effectiveness", 
                               "EIU" = "functioning_of_government",
                               "BTI" = "q14_steering_capability", 
                               "QOG" = "qs_impar"), 
         category = fct_relevel(category, "WGI", "BTI", "QOG", "EIU")) %>% 
  ggplot(aes(value, category)) +
  geom_boxplot() +
  geom_point(data = china_index_joined, aes(value, category), shape = 5, size = 3, color = "red") +
  labs(title = "Fig 7. China's bureaucracy in comparative perspective", 
       subtitle = "China's position on each index is marked as a diamond. The box and whisker plots show the normalized range of scores \nfor other measured countries.", 
       y = NULL, 
       x = NULL, 
       caption = "Source: Normalization and graph by author. \nData from EIU: Economist Intelligence Unit, QOG: Quality of Government Survey, BTI: Bertelsmann Transformation Index,\nWGI: World Bank Government Indicators") +
  theme(text = element_text(family = "Times"), 
        plot.title = element_text(face = "bold", size = 12), 
        plot.caption = element_text(hjust = 0)) +
  annotate("text", x = -.7, y = 1.2, label = "Government effectiveness", color = "black", family = "Times") +
  annotate("text", x = -.7, y = 2.2, label = "Steering capability", color = "black", family = "Times") +
  annotate("text", x = -.72, y = 3.2, label = "Impartial public administration", color = "black", family = "Times") +
  annotate("text", x = -.72, y = 4.2, label = "Functioning of government", color = "black", family = "Times")
ggsave(filename = "figs/china_bureaucracy-in-comparative-perspective.pdf", width = 8, height = 4)
  
```



```{r}
library(ggforce)

gdi_filtered <- gdi_raw %>% 
  filter(series_name %in% c("Government Effectiveness: Estimate", 
                            "Control of Corruption: Estimate", 
                            "Political Stability and Absence of Violence/Terrorism: Estimate", 
                            "Regulatory Quality: Estimate", 
                            "Rule of Law: Estimate", 
                            "Voice and Accountability: Estimate")) %>% 
  mutate_at(vars(matches("^x")), as.numeric) %>% 
  pivot_longer(cols = x1996_yr1996: x2019_yr2019, names_to = "year") %>% 
  mutate(year = as.numeric(str_extract(year, "\\d..."))) %>% 
  mutate(series_name = str_remove(series_name, ": Estimate"), 
         series_name = str_remove(series_name, "/Terrorism"))

gdi_filtered %>% 
  filter(country_name == "China") %>% 
  ggplot(aes(year, value, color = series_name)) +
  geom_line(size = 1) +
  geom_point(alpha = .8) +
  geom_vline(xintercept = 2013, lty = "dashed") +
  scale_x_continuous(limits = c(1995, 2020)) +
  #annotate("text", x = 2007, y = .4, label = "Xi came in here", color = "black", size = 3) +
  #annotate("curve", x = 2008, xend = 2012, y = .18, yend = .18, arrow = arrow(ends = "last", angle = 20, length = unit(.1, "inches"), type = "closed")) +
  facet_wrap(~ series_name) +
  labs(subtitle = "World Bank Governance Index: China (1996-2019)", 
       title = "Fig 8. Xi apparently changed China's bureaucratic landscape",
       x = NULL, 
       y = NULL, 
       caption = "Data Source: Worldwide Governance Index") +
  theme_bw() +
  theme(text = element_text(family = "Times"),
        plot.title = element_text(face = "bold", size = 12),
        legend.position = "none") 
ggsave(filename = "figs/how_xi_changed_china_political_landscape.pdf", width = 8, height = 4)

```



```{r}
gdi_2018 <- gdi_filtered %>% 
  filter(year == 2018)

polity_2018 <- polity_raw %>% 
  filter(year == 2018) %>% summary()

gdi_2018_polity_joined <- gdi_2018 %>% 
  left_join(polity_2018, by = c("country_name" = "country")) %>% 
  filter(!is.na(polity2)) %>% 
  select(country_name, series_name, value, polity2) 

gdi_2018_polity_joined %>% 
  filter(country_name == "China")

gdi_2018_polity_joined %>% 
  # filter(series_name == "Government Effectiveness") %>% 
  ggplot(aes(polity2, value)) +
  geom_point(alpha = .8) +
  geom_smooth(method = "loess") +
  geom_vline(xintercept = 5, lty = "dashed", color = "red") +
  geom_point(data = gdi_2018_polity_joined %>% 
  filter(country_name == "China"), aes(polity2, value), size = 3, color = "red") +
  facet_wrap(~ series_name) +
  theme_bw() +
  labs(title = "Putting China's governance in comparative context", 
       subtitle = "As of 2018", 
       x = "Polity IV",
       y = "WGI index") +
  theme(text = element_text(family = "Times"), 
        plot.title = element_text(face = "bold", size = 15)) 
ggsave(filename = "figs/putting_china_governance_in_compararive_context.pdf", width = 8, height = 5)
```




